# OTBS
unstable_features = true
edition = "2021"
reorder_imports = true
imports_granularity = "Crate"
use_small_heuristics = "Default"
comment_width = 100
wrap_comments = true
binop_separator = "Back"
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
hard_tabs = true
newline_style = "unix"
use_try_shorthand = true
version = "Two"
error_on_line_overflow = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
tab_spaces = 4
max_width = 125
match_block_trailing_comma = true
fn_args_layout = "Compressed"
indent_style = "Block"
imports_indent = "Block"
normalize_comments = true
force_multiline_blocks = true
reorder_impl_items = true
fn_single_line = false
where_single_line = true
brace_style = "PreferSameLine"
type_punctuation_density = "Compressed"
overflow_delimited_expr = true
condense_wildcard_suffixes = true
